# Generated by Django 4.2.6 on 2023-12-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_comment_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileImage', models.ImageField(upload_to='imgs/')),
                ('Email', models.EmailField(max_length=254)),
                ('DoB', models.DateField()),
            ],
        ),
    ]
