# Generated by Django 4.2.6 on 2023-12-15 02:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Favourite',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SPORTS', 'Sports'), ('FASHION', 'Fashion'), ('EDUCATION', 'Education'), ('ART', 'Art'), ('WORLDNEWS', 'World News'), ('FINANCE', 'Finance')], default='', max_length=9),
            preserve_default=False,
        ),
    ]
