# Generated by Django 4.2.6 on 2023-12-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='preview',
            field=models.CharField(default='No preview available', max_length=255),
        ),
    ]
